//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProjectV1 {
    
    
    public partial class Contact {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new WebProjectV1.SiteMaster Master {
            get {
                return ((WebProjectV1.SiteMaster)(base.Master));
            }
        }
    }
}
