// <auto-generated />
namespace WebProjectV1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addednewcustomercolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednewcustomercolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201612051355361_added new customer columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
